version: "3"
services:
    web:
        container_name: prueba_airzone_web
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 84:80
        volumes:
            - ./:/var/www
            - ./public:/var/www/html
    mysql:
        container_name: prueba_airzone_mysql
        image: mariadb:10.4.12
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - 3317:3306
